[package]
name = "xiefeng-shiying"
version = "0.3.0"
description = "撷风拾影 - 抖音视频下载桌面工具"
authors = ["chenwentao"]
# v0.3.0 起：项目协议由 MIT 切换为 Apache License 2.0
license = "Apache-2.0"
edition = "2021"

[lib]
name = "xiefeng_shiying_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-ico"] }
tauri-plugin-window-state = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
open = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
